#!/usr/bin/env Rscript

t1 <- read.delim("t1", header=F)
t2 <- read.delim("t2", header=F)
x <- merge(t1, t2, by.x=1, by.y=1, all=T)$V2.x
y <- merge(t1, t2, by.x=1, by.y=1, all=T)$V2.y

x[is.na(x)] <- 0
y[is.na(y)] <- 0

cbind(x,y)
