#!/usr/bin/env Rscript

data <- "uniprot_2011_02_remaining90.tab"
size <- as.numeric(system(paste('cat', data, ' | wc -l'), intern=T))
part <- 1/100

set.seed(1)
x <- sample(1:size, size * part)
write(x, "sample-1-percent-id-numbers", sep = "\n")
