#!/usr/bin/env ruby

require 'open3'

require 'rubygems'
require 'redis'

#
# Takes a frequencies file.
# Loads it into a Redis hash.

# This IP is configured in redis.cone (originally :port => 6379)
redis = Redis.new(:host => "192.168.3.27", :port => 6380, :timeout => 600)

if !(ARGV.size == 2 or (ARGV.size == 3 and ARGV[2] == '-f'))
  STDERR.puts "USAGE: 043-load-freqs-to-redis <freqs-file> <hash-name>"
  exit 1
end

FREQS_FILE = ARGV[0]
HASH_NAME  = ARGV[1]


if redis.exists HASH_NAME and !(ARGV[2] == '-f')
  STDERR.puts "ERROR: The hash #{HASH_NAME} already in the data store"
  STDERR.puts "       add -f argument to force adding to the existing counts"
  exit
end

File.open(FREQS_FILE) do |f|
  f.each do |line|
    nmer, frequency = line.chomp.split("\t")
    redis.hset HASH_NAME, nmer, frequency
  end
end
