#!/bin/bash

for p in `seq 2 6`; do
  echo "time cat uniprot_2011_02_remaining90.tab | \
    ./061-classify-in-ruby $p > \
    class-predictions-${p}p-rem90-biol" | \
    qsub -l nodes=1:ppn=1 -N class-${p}p-rem90-biol -d `pwd`

  echo "time cat shuffled-remaining90.tab | \
    ./061-classify-in-ruby $p > \
    class-predictions-${p}p-rem90-biol" | \
    qsub -l nodes=1:ppn=1 -N class-${p}p-rem90-shuf -d `pwd`

done
