#!/usr/bin/env Rscript

runlen <- commandArgs(trailingOnly=T)[[1]]

cat("Loading Data...\n")
n <- read.delim(paste(sep="", "frequencies-", runlen, "p-sample-tmp"), header=F)
s <- read.delim(paste(sep="", "frequencies-", runlen, "p-shuffled-tmp"), header=F)

m <- merge(n, s, by.x=1, by.y=1, all=T)
x <- m$V2.x
y <- m$V2.y
x[is.na(x)] <- 0.5
y[is.na(y)] <- 0.5

cat("Plotting...\n")
output_file_png <- paste(sep="", "fig-", runlen, ".png")
output_file_svg <- paste(sep="", "fig-", runlen, ".svg")
#svg(output_file_svg)
png(output_file_png, height=1000, width=1000, unit="px", pointsize=13)

par(mar=c(10, 10, 2, 2))



plot(x, y, log="xy",  axes=FALSE, ylab="", xlab="")


axis(1,signif(exp(0:200), 2), las=2)
axis(2,signif(exp(0:200), 2), las=2)

abline(
  v=c(1,2.72,7.39,20.1,54.6,148,403,1.1e+3,
      2.98e+3,8.1e+3,2.2e+4,5.99e+4,1.63e+5,4.42e+5,1.2e+6,3.27e+6),
  h=c(1,2.72,7.39,20.1,54.6,148,403,1.1e+3,
      2.98e+3,8.1e+3,2.2e+4,5.99e+4,1.63e+5,4.42e+5,1.2e+6,3.27e+6),
  lty=3, col="gray")

abline(0, 1, col = "red", lwd = 2)

dev.off()
