#!/bin/bash

set -v

#time ./001-generate-random-10-percent-sample-ids

time cat uniprot_2011_02.tab |  
 ./002-extract-10-percent-sample > \
 uniprot_2011_02_sample.tab 

#time ./003-get-pattern-frequencies
