#!/bin/bash

for p in 3; do
  for s in `seq 1 10`; do
    echo "time cat uniprot_2011_02_sample.tab | \
    ./041-get-spaced-seed-freqs $p $s > seed-frequencies-${p}p/s$s-biol" | 
    qsub -l nodes=1:ppn=1 -N freq-${p}p-seed$s-biol -d `pwd`

    echo "time cat shuffled-sample.tab | \
    ./041-get-spaced-seed-freqs $p $s > seed-frequencies-${p}p/s$s-shuf" | 
    qsub -l nodes=1:ppn=1 -N freq-${p}p-seed$s-shuf -d `pwd`
  done
done
